export const ADD_REVIEW = "ADD_REVIEW";

export const REMOVE_REVIEW = "REMOVE_REVIEW";

export const EDIT_REVIEW = "EDIT_REVIEW";

export const SAVE_RESTAURAUNT = "SAVE_RESTAURAUNT";

export const REMOVE_RESTAURAUNT = "REMOVE_RESTAURAUNT";

